---
- name: Testing andrewrothstein.kops
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'kops version'
      ansible.builtin.command: kops version
      changed_when: false
      register: kops_test_output
    - name: Output from 'kops version'
      ansible.builtin.debug:
        msg: '{{ kops_test_output.stdout }}'
