---
- hosts: all
  roles:
    - role: '{{playbook_dir}}'
  tasks:
    - command: /usr/local/bin/kops version
      register: kops_test_output
    - name: kops version
      debug:
        msg: '{{ kops_test_output.stdout }}'
